title: Cristin Connerney
description: > # this means to ignore newlines until "baseurl:"
  Cristin Connerney's data science portfolio
permalink: ':title/'
url: "https://cconnerney.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cristin Connerney # add your name
author-img: cmu.jpg # add your photo
about-author: Data science graduate student at Carnegie Mellon University # add description
social-github: cconnerney # add your Github handle
social-linkedin: cconnerney # add your Linkedin handle
social-email: cristinconnerney@cmu.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-gist
 
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
